export const actions = {
  ADD_TODO_TO_LIST: "ADD_TODO_TO_LIST",
  SET_TODO_ITEM_DONE: "SET_TODO_ITEM_DONE",
  REMOVE_TODO_FROM_LIST: "REMOVE_TODO_FROM_LIST",
  ON_SEARCH_BOOK: "ON_SEARCH_BOOK",
  SET_USERNAME: "SET_USERNAME",
  REMOVE_USERNAME: "REMOVE_USERNAME",
};
